import Link from "next/link";

const services=[
 {icon:"🏠",title:"Nettoyage courant des bâtiments",text:"Maisons, appartements, encombrants, remise en état, succession et débarras.",items:["Ménage complet","Remise en état","Débarras / succession","Enlèvement d'encombrants"]},
 {icon:"🏡",title:"Nettoyage toiture & façade",text:"Démoussage, traitement hydrofuge et nettoyage haute pression selon le support.",items:["Toitures tuiles / ardoises","Façades et murs","Traitement hydrofuge","Protection durable"]},
 {icon:"🛠️",title:"Petit bricolage & dépannage",text:"Des interventions pratiques pour entretenir, réparer, monter ou remettre en état.",items:["Petite maçonnerie","Plomberie et fuites","Peinture intérieur / extérieur","Montage et réparations"]},
 {icon:"🌿",title:"Entretien général & espaces verts",text:"Entretien courant des extérieurs et petits travaux de terrain.",items:["Tonte de pelouse","Taille de haies","Débroussaillage","Parties communes"]},
];

export default function Home(){
 return <main>
  <section className="hero-grid relative overflow-hidden bg-gradient-to-br from-navy-50 via-white to-brand-50">
    <div className="absolute -right-28 -top-24 h-96 w-96 rounded-full bg-brand-300/25 blur-3xl"/>
    <div className="container grid min-h-[720px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr]">
      <div className="animate-fadeUp">
        <span className="inline-flex rounded-full border border-navy-200 bg-white px-4 py-2 text-xs font-bold uppercase tracking-[.22em] text-navy-700 shadow-soft">Devis gratuit · Saintes & alentours</span>
        <h1 className="mt-6 font-black tracking-tight text-5xl leading-[.95] text-navy-900 sm:text-6xl lg:text-8xl">Vos travaux et votre maison <span className="text-brand-700">en de bonnes mains.</span></h1>
        <p className="mt-6 max-w-2xl text-lg leading-relaxed text-navy-900/65 sm:text-xl">Nettoyage, entretien, petits travaux et espaces verts : un interlocuteur unique pour garder votre intérieur et votre extérieur toujours au top.</p>
        <div className="mt-8 flex flex-wrap gap-3"><Link href="#devis" className="rounded-full bg-navy-700 px-7 py-3.5 font-bold text-white shadow-soft hover:bg-navy-900 transition">Demander un devis gratuit</Link><a href="tel:0615646880" className="rounded-full border border-navy-200 bg-white px-7 py-3.5 font-bold text-navy-700 hover:border-brand-300 transition">📞 Appeler</a></div>
        <div className="mt-10 grid max-w-xl grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-white p-4 shadow-soft"><b className="block text-2xl text-navy-700">60 km</b><span className="text-xs text-navy-900/55">autour de Saintes</span></div><div className="rounded-2xl bg-white p-4 shadow-soft"><b className="block text-2xl text-brand-700">4</b><span className="text-xs text-navy-900/55">grands pôles de services</span></div><div className="rounded-2xl bg-white p-4 shadow-soft"><b className="block text-2xl text-navy-700">0 €</b><span className="text-xs text-navy-900/55">pour le devis</span></div></div>
      </div>
      <div className="relative mx-auto w-full max-w-xl">
        <div className="animate-float relative rounded-[36px] border border-white/80 bg-white/75 p-4 shadow-2xl backdrop-blur">
          <div className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-sky-100 via-white to-brand-100 aspect-[4/3]">
            <svg viewBox="0 0 600 450" className="absolute inset-0 h-full w-full" aria-hidden>
              <rect width="600" height="450" fill="#eaf5ff"/><circle cx="490" cy="95" r="50" fill="#fff" opacity=".9"/>
              <path d="M0 310 C130 250 220 270 330 245 C450 215 510 255 600 225 L600 450 L0 450Z" fill="#9ed970"/>
              <path d="M80 300 L250 165 L420 300" fill="#0b4d80"/><path d="M110 295 L250 185 L392 295" fill="#fff"/>
              <path d="M150 300 V245 H350 V300" fill="#e7f7ed"/><rect x="225" y="255" width="55" height="45" rx="4" fill="#0b4d80"/>
              <rect x="165" y="232" width="40" height="30" rx="4" fill="#72b7ea"/><rect x="300" y="232" width="40" height="30" rx="4" fill="#72b7ea"/>
              <path d="M0 365 H600" stroke="#fff" stroke-width="10" opacity=".8"/><path d="M30 390 H570" stroke="#59b52e" stroke-width="6"/>
              <circle cx="520" cy="320" r="34" fill="#2f871e"/><path d="M500 327 Q520 285 540 327" fill="#fff"/><path d="M520 289 V340" stroke="#fff" stroke-width="6"/>
            </svg>
            <div className="absolute bottom-4 left-4 rounded-2xl bg-white/92 px-4 py-3 shadow-soft"><p className="text-xs uppercase tracking-widest text-navy-700/50">LUDOBRICOPRO</p><p className="font-bold text-navy-900">Un seul pro, pour tout entreprendre</p></div>
          </div>
        </div>
        <div className="absolute -bottom-5 -right-4 rounded-3xl bg-navy-700 px-6 py-4 text-center text-white shadow-xl"><strong className="block text-2xl">Devis</strong><span className="font-black text-brand-300">GRATUIT</span></div>
      </div>
    </div>
  </section>

  <section id="services" className="container py-20 sm:py-28">
    <div className="mx-auto max-w-3xl text-center"><span className="text-xs font-bold uppercase tracking-[.3em] text-brand-700">Nos prestations</span><h2 className="mt-3 text-4xl font-black tracking-tight text-navy-900 sm:text-5xl">Un seul professionnel pour plusieurs besoins</h2><p className="mt-4 text-lg text-navy-900/55">Des interventions claires, de proximité, avec un devis adapté à votre besoin.</p></div>
    <div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{services.map(s=><article key={s.title} className="service-card rounded-3xl border border-slate-200 bg-white p-6 shadow-soft"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-navy-700 to-brand-500 text-3xl">{s.icon}</div><h3 className="mt-5 text-xl font-black text-navy-900">{s.title}</h3><p className="mt-3 text-sm leading-relaxed text-navy-900/55">{s.text}</p><ul className="mt-5 space-y-2 text-sm">{s.items.map(i=><li key={i} className="flex gap-2"><span className="font-black text-brand-700">✓</span><span>{i}</span></li>)}</ul></article>)}</div>
  </section>

  <section id="realisations" className="bg-navy-900 py-20 text-white sm:py-28">
    <div className="container"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><span className="text-xs font-bold uppercase tracking-[.3em] text-brand-300">Réalisations</span><h2 className="mt-3 text-4xl font-black sm:text-5xl">Montrez vos travaux. Faites parler le résultat.</h2><p className="mt-4 text-white/60">Cette galerie est préparée pour accueillir tes vraies photos de chantiers et tes avant / après.</p></div><div className="grid grid-cols-2 gap-4"><div className="aspect-[4/3] rounded-3xl bg-gradient-to-br from-sky-200 to-sky-50 p-5 text-navy-900"><div className="flex h-full items-end"><span className="rounded-xl bg-white/80 px-3 py-2 text-sm font-bold">Avant / après · à remplacer par tes photos</span></div></div><div className="aspect-[4/3] rounded-3xl bg-gradient-to-br from-brand-300 to-brand-50 p-5 text-navy-900"><div className="flex h-full items-end"><span className="rounded-xl bg-white/80 px-3 py-2 text-sm font-bold">Toiture · façade · entretien</span></div></div></div></div></div>
  </section>

  <section id="zone" className="container py-20 sm:py-28"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><span className="text-xs font-bold uppercase tracking-[.3em] text-brand-700">Zone d'intervention</span><h2 className="mt-3 text-4xl font-black text-navy-900 sm:text-5xl">Saintes et jusqu'à environ 60 km autour</h2><p className="mt-5 max-w-xl text-lg leading-relaxed text-navy-900/60">Le site peut ensuite être enrichi avec une vraie carte interactive et une liste des communes desservies. Pour l'instant, la zone annoncée reste volontairement simple et lisible.</p><div className="mt-7 flex flex-wrap gap-2">{["Saintes","Cognac","Pons","Royan","Saint-Jean-d'Angély","Pont-l'Abbé-d'Arnoult"].map(v=><span key={v} className="rounded-full border border-navy-100 bg-white px-4 py-2 text-sm font-semibold shadow-sm">{v}</span>)}</div></div><div className="rounded-[32px] border border-navy-100 bg-gradient-to-br from-navy-50 to-brand-50 p-6 shadow-soft"><svg viewBox="0 0 520 340" className="w-full" aria-label="Carte stylisée de la zone"><path d="M80 130 L150 70 L250 85 L330 55 L430 115 L390 210 L320 250 L235 280 L150 240 L90 195 Z" fill="#dceeff" stroke="#1671b8" stroke-width="5"/><circle cx="250" cy="170" r="28" fill="#59b52e" stroke="#fff" stroke-width="7"/><text x="250" y="176" text-anchor="middle" fill="#073455" font-size="18" font-weight="800">Saintes</text><circle cx="250" cy="170" r="60" fill="none" stroke="#59b52e" stroke-opacity=".35" stroke-width="4"/><circle cx="250" cy="170" r="100" fill="none" stroke="#1671b8" stroke-opacity=".25" stroke-width="4"/></svg></div></div></section>

  <section id="devis" className="bg-gradient-to-br from-brand-50 via-white to-navy-50 py-20 sm:py-28">
    <div className="container"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><span className="text-xs font-bold uppercase tracking-[.3em] text-brand-700">Devis gratuit</span><h2 className="mt-3 text-4xl font-black text-navy-900 sm:text-5xl">Décrivez-nous votre besoin</h2><p className="mt-4 text-lg leading-relaxed text-navy-900/60">Remplissez le formulaire : il prépare automatiquement un e-mail à envoyer à LUDOBRICOPRO.</p><div className="mt-8 rounded-3xl bg-navy-900 p-6 text-white shadow-soft"><p className="font-black">📞 06 15 64 68 80</p><p className="mt-2 text-white/60">✉ ludo172300@gmail.com</p><p className="mt-2 text-white/60">📍 Saintes · environ 60 km autour</p></div></div><div className="rounded-[30px] border border-slate-200 bg-white p-6 shadow-soft sm:p-8"><form action="mailto:ludo172300@gmail.com" method="post" encType="text/plain" className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Nom<input name="Nom" required className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-brand-500" /></label><label className="text-sm font-semibold">Téléphone<input name="Telephone" required className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-brand-500" /></label></div><label className="text-sm font-semibold">E-mail<input type="email" name="Email" required className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-brand-500" /></label><label className="text-sm font-semibold">Prestation<select name="Prestation" className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-brand-500"><option>Nettoyage</option><option>Toiture / façade</option><option>Petit bricolage / dépannage</option><option>Entretien / espaces verts</option><option>Autre</option></select></label><label className="text-sm font-semibold">Message<textarea name="Message" rows={6} required className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-brand-500" placeholder="Décrivez les travaux, la commune et les contraintes éventuelles…"/></label><button className="rounded-full bg-brand-700 px-6 py-3.5 font-black text-white hover:bg-brand-900 transition">Préparer ma demande de devis</button><p className="text-xs text-navy-900/45">L'envoi utilise votre messagerie. Un vrai formulaire serveur pourra être branché ensuite (Resend, Brevo, etc.).</p></form></div></div></div>
  </section>

  <section className="container py-20 sm:py-24"><div className="rounded-[34px] bg-gradient-to-r from-navy-700 via-navy-700 to-brand-700 p-7 text-white shadow-soft sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="text-xs font-bold uppercase tracking-[.3em] text-brand-300">Contact</span><h2 id="contact" className="mt-2 text-3xl font-black sm:text-5xl">Un projet ? Parlons-en.</h2><p className="mt-4 max-w-2xl text-white/70">Réactivité, proximité et sérénité pour vos travaux et votre entretien.</p></div><div className="flex flex-wrap gap-3"><a href="tel:0615646880" className="rounded-full bg-white px-6 py-3 font-black text-navy-700">📞 06 15 64 68 80</a><a href="mailto:ludo172300@gmail.com" className="rounded-full border border-white/20 bg-white/10 px-6 py-3 font-black text-white">✉ Écrire</a></div></div></div></section>

 </main>
}
